---

- block:

  - name: Create the image storage directory if it does not exist
    ansible.builtin.file:
      path: "{{ pi_image_dir }}"
      state: directory
      mode: '0755'

  - name: Download pi image
    ansible.builtin.get_url:
      url: "{{ pi_image_url }}/{{ pi_image_name }}"
      dest: "{{ pi_image_dir }}/{{ pi_image_name }}.zip"
      mode: '0644'

  - name: Unarchive pi image
    ansible.builtin.unarchive:
      src: "{{ pi_image_dir }}/{{ pi_image_name }}.zip"
      dest: "{{ pi_image_dir }}"
    register: unzip_result

  - name: unzip results
    ansible.builtin.debug:
      var: unzip_result.extract_results
      verbosity: 1
    when: unzip_result is defined

  tags:
    - download
    - all
 

