---

- block:

  - name: Create the image storage directory if it does not exist
    ansible.builtin.file:
      path: "{{ pi_image_dir }}"
      state: directory
      mode: '0755'

  # - name: Download pi image
  #   ansible.builtin.get_url:
  #     url: "{{ pi_image_url }}"
  #     dest: "{{ pi_image_dir }}/{{ pi_image_name }}.xz"
  #     mode: '0644'

  - name: Check that the archive exists
    stat:
      path: "{{ pi_image_dir }}/{{ pi_image_name }}"
    register: stat_result

  - name: Unarchive pi image
    ansible.builtin.shell: "unxz {{ pi_image_name }}.xz"
    args:
      chdir: "{{ pi_image_dir }}"
    register: xz_results
    when: not stat_result.stat.exists

  - name: Debug Unarchive results
    ansible.builtin.debug:
      var: xz_results
      verbosity: 1
    when: xz_results is defined

  tags:
    - download
    - all
 

