---


- name: Display original cmdline.txt
  debug: 
    msg: "{{ lookup('/tmp/pi_image/boot/cmdline.txt', ca_certificate_file) }}"


- name: Enable cgroup on Pi
  ansible.builtin.copy:
    src: cmdline_cgroup.txt
    dest: "{{ pi_image_boot_mount }}/cmdline.txt"
    mode: '0644'
  when: pi_image_setup_cgroup is defined and pi_image_setup_cgroup is True
  become: True
  tags:
    - configure
    - all


