---

- name: Enable ssh
  ansible.builtin.file:
    path: "{{ pi_image_boot_mount }}/ssh"
    state: touch
    mode: '0755'
  when: pi_image_setup_ssh is defined and pi_image_setup_ssh is True
  become: true
  tags:
    - configure
    - all
 
