---

- block:

  - name: Unmount root partition
    ansible.posix.mount:
      path: "{{ pi_image_rootfs_mount }}"
      src: "/dev/mapper/loop0p2"
      fstype: auto
      state: absent
    #become: yes

  - name: Unmount boot partition
    ansible.posix.mount:
      path: "{{ pi_image_boot_mount }}"
      src: "/dev/mapper/loop0p1"
      fstype: auto
      state: absent
    #become: yes

  - name: Remove the boot mount directory if it does not exist
    ansible.builtin.file:
      path: "{{ pi_image_boot_mount }}"
      state: absent

  - name: Remove a rootfs if it does not exist
    ansible.builtin.file:
      path: "{{ pi_image_rootfs_mount }}"
      state: absent

  - name: Remove the loop from the image file
    ansible.builtin.command:
      cmd: "/usr/sbin/kpartx -d {{ pi_os_image }}"
    register: kpartx_result
    become: yes
    
  - name: kpartx results
    ansible.builtin.debug:
      var: kpartx_result
      verbosity: 1
    when: kpartx_result is defined

  tags:
    - umount
    - all
 
